name: around_the_frog
description: "Around the Frog"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_3d_controller: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_cube: ^0.1.1
  http: ^1.2.2
  firebase_storage: ^12.3.2
  firebase_core: ^3.6.0
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.3
  cloud_firestore: ^5.4.4
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  firebase_database: ^11.1.4
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/teapot.obj
